fix time zone rotate
mosn/pkg pull request #21
Opened 2020-11-03 08:17 UTC by nejisama

2020-11-03 08:35 UTC, cch123 commented
parse 用这个库可以避免写错 layout，不过这里就先这样吧

https://github.com/araddon/dateparse

2020-11-03 08:45 UTC, cch123 commented on utils/syscall_test.go
> +		fisrtTimeStr := "2020-11-01 00:00:00 -0700 PDT"
fisrtTimeStr
firstTimeStr

2020-11-03 08:46 UTC, cch123 commented on utils/syscall_test.go
> +		if d != 25*time.Hour { // rollback an hour, so next day is 25 hour
assert.Equal(t, d, 25*time.Hour)

2020-11-03 08:46 UTC, cch123 commented on utils/syscall_test.go
> +		if d2 != 23*time.Hour { // dst, next day is 23 hour
ssert.Equal(t, d2, 23*time.Hour)

2020-11-03 08:47 UTC, cch123 commented on utils/syscall_test.go
> +		fisrtTimeStr := "2020-11-01 00:00:00 +0000 UTC"
fisrtTimeStr
first

2020-11-03 09:04 UTC, cch123 requested changes
PTAL

2020-11-04 01:58 UTC, taoyuanyuan approved these changes
LGTM

2020-11-04 07:58 UTC, nejisama commented on utils/syscall_test.go
> +		fisrtTimeStr := "2020-11-01 00:00:00 -0700 PDT"
fixed

2020-11-04 07:58 UTC, nejisama commented on utils/syscall_test.go
> +		if d != 25*time.Hour { // rollback an hour, so next day is 25 hour
fixed

2020-11-04 07:58 UTC, nejisama commented on utils/syscall_test.go
> +		if d2 != 23*time.Hour { // dst, next day is 23 hour
no assert vendor

2020-11-04 07:58 UTC, nejisama commented on utils/syscall_test.go
> +		fisrtTimeStr := "2020-11-01 00:00:00 +0000 UTC"
fixed

2020-11-04 07:59 UTC, nejisama commented
> parse 用这个库可以防止写错 layout，不过这里就先这样吧
> 
> https://github.com/araddon/dateparse

基础库没有必要引用太多的其他的库

2020-11-04 11:40 UTC, cch123 approved these changes

2020-11-04 11:40 UTC, merged